
# See https://github.com/marketplace/actions/simple-issue-labeler
  
name: label-untriaged-issues

on:
  schedule:
    - cron: "* * 1 * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Automatically marked uncategorized issue as product feedback'
          stale-issue-label: 'product-feedback'
          exempt-issue-labels: 'doc-bug,doc-enhancement,doc-idea,product-issue,product-question'
          days-before-issue-stale: 30
